#!/usr/bin/env python3
"""Generate the churny, append-only catalog sub-indexes from frontmatter.

The master catalog (docs/README.md) is read on every session bootstrap, so
the high-churn, point-in-time sections must not accumulate hand-written
paragraphs there. This script derives two index files from each artifact's
frontmatter, so they cannot rot into bloat and demotion is automatic:

  - docs/analysis/README.md            from docs/analysis/*.md
  - docs/exec-plans/completed/README.md from docs/exec-plans/completed/*.md

Analysis rows split into Current / Superseded by the `superseded-by:`
frontmatter pointer (relevance is a relationship, not a date).

Modes:
  (default)  regenerate both index files in place.
  --check    regenerate in memory and compare to disk; exit 1 on drift.
             Wire this into pre-commit (fail-fast, no mid-commit mutation).
  --dry-run  print what would be written; always exit 0.

Bypass: set HARNESS_BYPASS="<reason>" to short-circuit with exit 0.

The script is stdlib-only and discovers the repo root by walking up from this
file (assumes install path scripts/harness/). See ADR
generated-catalog-subindexes.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/harness/generate_catalog_indexes.py "
    "— do not edit by hand.\n"
    "     Edit the source artifacts' frontmatter and regenerate. "
    "See ADR generated-catalog-subindexes. -->\n"
)

EXCLUDED_NAMES = {"readme.md", "_template.md"}


def front_matter_block(content: str) -> str:
    if not content.startswith("---\n"):
        return ""
    end_index = content.find("\n---\n", 4)
    if end_index == -1:
        return ""
    return content[4:end_index]


def clean_value(value: str) -> str:
    value = re.sub(r"\s+#.*$", "", value).strip()
    return value.strip('"').strip("'").strip()


def parse_front_matter(content: str) -> dict[str, str]:
    block = front_matter_block(content)
    metadata: dict[str, str] = {}
    for raw_line in block.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        metadata[key.strip()] = clean_value(value)
    return metadata


def first_heading(content: str) -> str:
    for line in content.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def relative(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


@dataclass(frozen=True)
class AnalysisRow:
    name: str
    title: str
    date: str
    summary: str
    superseded_by: str


@dataclass(frozen=True)
class PlanRow:
    name: str
    title: str
    date: str
    plan_id: str
    features: str
    summary: str


def iter_docs(directory: Path) -> list[Path]:
    if not directory.exists():
        return []
    return sorted(
        path
        for path in directory.glob("*.md")
        if not path.is_symlink()
        and path.is_file()
        and path.name.lower() not in EXCLUDED_NAMES
    )


def collect_analysis(directory: Path) -> list[AnalysisRow]:
    rows: list[AnalysisRow] = []
    for path in iter_docs(directory):
        content = path.read_text(encoding="utf-8")
        meta = parse_front_matter(content)
        topic = meta.get("topic", "") or first_heading(content) or path.stem
        rows.append(
            AnalysisRow(
                name=path.name,
                title=topic,
                date=meta.get("date", ""),
                summary=meta.get("summary", ""),
                superseded_by=meta.get("superseded-by", ""),
            )
        )
    # newest first; blank/invalid dates sort last
    rows.sort(key=lambda r: (r.date or "0000-00-00"), reverse=True)
    return rows


def collect_plans(directory: Path) -> list[PlanRow]:
    rows: list[PlanRow] = []
    for path in iter_docs(directory):
        content = path.read_text(encoding="utf-8")
        meta = parse_front_matter(content)
        title = first_heading(content) or meta.get("slug", "") or path.stem
        rows.append(
            PlanRow(
                name=path.name,
                title=title,
                date=meta.get("date", ""),
                plan_id=meta.get("id", ""),
                features=meta.get("features", "").strip("[]").strip(),
                summary=meta.get("summary", ""),
            )
        )
    rows.sort(key=lambda r: (r.date or "0000-00-00"), reverse=True)
    return rows


def render_analysis_index(rows: list[AnalysisRow]) -> str:
    current = [r for r in rows if not r.superseded_by]
    superseded = [r for r in rows if r.superseded_by]

    lines = [
        GENERATED_HEADER,
        "# Analysis Index",
        "",
        "Point-in-time research, gap reports, investigations — newest first. "
        "Generated from `docs/analysis/*.md` frontmatter "
        "(`topic`, `date`, `summary`, `superseded-by`).",
        "",
        "## Current",
        "",
    ]
    if current:
        for r in current:
            summary = r.summary or "_(no summary; add a `summary:` line)_"
            lines.append(f"- [{r.title}]({r.name}) — {summary} (`{r.date}`)")
    else:
        lines.append("_(none)_")

    lines.extend(["", "## Superseded", ""])
    if superseded:
        lines.append(
            "Retained for provenance; skip during tag-loading unless the "
            "superseding doc points you back."
        )
        lines.append("")
        for r in superseded:
            summary = r.summary or "_(no summary)_"
            target = r.superseded_by
            lines.append(
                f"- [{r.title}]({r.name}) — {summary} → superseded by "
                f"[`{target}`](../../{target}) (`{r.date}`)"
            )
    else:
        lines.append("_(none)_")

    return "\n".join(lines) + "\n"


def render_plans_index(rows: list[PlanRow]) -> str:
    lines = [
        GENERATED_HEADER,
        "# Completed Plans Index",
        "",
        "Shipped ExecPlans — newest first. Generated from "
        "`docs/exec-plans/completed/*.md` frontmatter. Retained for "
        "historical context; plans are mutable via amendment "
        "(see ADR post-completion-amendment).",
        "",
    ]
    if rows:
        for r in rows:
            tail = []
            if r.plan_id:
                tail.append(f"`{r.plan_id}`")
            if r.features:
                tail.append(f"feat: {r.features}")
            tail.append(f"`{r.date}`")
            suffix = " — ".join(tail)
            summary = f"{r.summary} — " if r.summary else ""
            lines.append(f"- [{r.title}]({r.name}) — {summary}{suffix}")
    else:
        lines.append("_(none yet)_")

    return "\n".join(lines) + "\n"


def targets() -> list[tuple[Path, str]]:
    analysis_rows = collect_analysis(REPO_ROOT / "docs" / "analysis")
    plan_rows = collect_plans(REPO_ROOT / "docs" / "exec-plans" / "completed")
    return [
        (REPO_ROOT / "docs" / "analysis" / "README.md",
         render_analysis_index(analysis_rows)),
        (REPO_ROOT / "docs" / "exec-plans" / "completed" / "README.md",
         render_plans_index(plan_rows)),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the analysis and completed-plan catalog indexes."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare generated output to disk; exit 1 on drift. For pre-commit.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print intended output; always exit 0.",
    )
    args = parser.parse_args()

    bypass = os.environ.get("HARNESS_BYPASS", "").strip()
    if bypass:
        sys.stderr.write(
            f"HARNESS_BYPASS set ({bypass!r}); skipping index generation.\n"
        )
        return 0

    drift: list[str] = []
    for path, content in targets():
        if args.dry_run:
            print(f"# would write {relative(path)}\n{content}")
            continue
        if args.check:
            existing = (
                path.read_text(encoding="utf-8") if path.exists() else None
            )
            if existing != content:
                drift.append(relative(path))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {relative(path)}")

    if args.check and drift:
        sys.stderr.write(
            "Catalog index drift detected in:\n"
            + "".join(f"  - {d}\n" for d in drift)
            + "Run: python scripts/harness/generate_catalog_indexes.py\n"
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
